### ISSUE TITLE
Not working on Windows Server 2019 17763.rs5_release.180914-1434

### ISSUE THREAD

**Issue by markoverholser** [nccgroup/SocksOverRDP#1]
I downloaded the x64 version and I am having trouble running it on a domain-joined Windows Server 2019 instance with RDP enabled. When I run `SocksOverRDP-Server.exe -v` I get the following error:

`[-] Could not open Dynamic Virtual Channel: 1  00000001`

It is the x64 version of Windows. I have tried both the x86 and x64 versions of the binary. The Microsoft Visual C++ Runtime libraries are installed. This is server-side only. The client-side DLL appears to load fine after registering on my Windows 10 client machine.

It's a lab environment, so I'm comfortable breaking stuff with you if you want me to try things.

**Comment by earthquake** [comment]
Have you connected to the server over remote desktop? With the remote desktop client and that popped up a messagebox showing the module was loaded?

**Comment by markoverholser** [comment]
Haha, that was dumb of me! It was not clear (to me) from the instructions that I needed to connect to the RDP server, _then_ start up the server side of things. That did the trick. Should I submit a suggested update to the readme?

**Comment by earthquake** [comment]
If you think that would clear up for others, then please do!

**Comment by earthquake** [comment]
This issue was a non-issue, and considered closed.
