### ISSUE TITLE
windows for arm client supper

### ISSUE THREAD

**Issue by killdayu** [nccgroup/SocksOverRDP#10]
I want to run it on window for arm virtual machine, because i am using apple m1 chip, thanks.

**Comment by earthquake** [comment]
have you tried to compile it form arm? I am unsure when can I pick this up, so it might be easier and quicker if you try.

**Comment by earthquake** [comment]
Amended the project files, added ARM64, which compiles to that platform. Although the regsvr32 raises an error at installation, which I could not figure out, it works properly.

You can either compile from source or use the ARM64 binaries that were added to the release section. Enjoy!
