### ISSUE TITLE
Support for linux systems

### ISSUE THREAD

**Issue by mjmichael73** [nccgroup/SocksOverRDP#12]
Thanks for your efforts, Is there anyway to add support for linux client machines ?

**Comment by RoganDawes** [comment]
Would be nice to have Mac support, since MS has their Remote Desktop Client for Mac. But that is quite a diversion from the existing platform support - it would need a whole new platform implementation!

**Comment by earthquake** [comment]
I would advise to look into xfreerdp, which already has support for Linux and other unices. This repo is purely for Windows at the moment and it is unlikely to change, except if proper funding is offered in exchange for the coding time.
