### ISSUE TITLE
Precompiled x64 dll for release 1.0 triggered windows defender protection

### ISSUE THREAD

**Issue by moihn** [nccgroup/SocksOverRDP#13]
Virus is detected in the downloaded release 1.0 x64 package.
![image](https://github.com/nccgroup/SocksOverRDP/assets/7393739/ba992b9d-ac45-4d3d-88f7-b2414e39caf6)

**Comment by earthquake** [comment]
Even the name of the virus states that the signature was generated for this project. Unfortunately Microsoft and other companies look at this tool as a malware. If you want this not to be found you can do two things:
- change the industry
- recompile from source without the signature included
