### ISSUE TITLE
Unable to Load Dynamic Virtual Channel DLL in Microsoft Remote Desktop Application

### ISSUE THREAD

**Issue by hanexthink** [nccgroup/SocksOverRDP#15]
We are experiencing an issue where the dynamic virtual channel (DVC) DLL cannot be loaded when using the Microsoft Remote Desktop application downloaded from the Microsoft Store.

1. Download and install the Microsoft Remote Desktop application from the Microsoft Store.
2. Run the same steps mentioned in the GitHub repo  
3. Make a remote desktop connection using the  the Microsoft Remote Desktop application from the Microsoft Store.

**Comment by earthquake** [comment]
Hi @hanexthink,

Feel free to include technical details into this thread including your results on inspecting the loading with procmon. I have a feeling that this might come from that the dll is not signed, therefore the Microsoft Store application will not load it. If that is the case, this won't be resolved.

**Comment by hanexthink** [comment]
Hi @earthquake ,

We noticed that not all Microsoft products provide support for Third-party virtual channel plugins. Please refer to the following link for detailed information:
[Compare Remote Desktop Clients](https://learn.microsoft.com/en-us/azure/virtual-desktop/compare-remote-desktop-clients?pivots=azure-virtual-desktop).

The provided table clearly indicates the supported and unsupported features across various platforms. As highlighted, Third-party virtual channel plugins are not universally supported across all versions and platforms. Specifically, this issue can be closed since we now know that DVC is not supported for macOS and Windows (RD Store).
<img width="1146" alt="image" src="https://github.com/nccgroup/SocksOverRDP/assets/35567025/4abb4483-9064-4143-8b5a-81e62a1e9e85">

Kind regards,
Hossein

**Comment by earthquake** [comment]
Thanks for the clarification, great job at investigating it. Hopefully this will be useful for other users.
