### ISSUE TITLE
 SocksOverRDP-Server.exe: Could not open Dynamic Virtual Channel: 1  00000001

### ISSUE THREAD

**Issue by bokandbok** [nccgroup/SocksOverRDP#2]
Hi,

The SocksOverRDP-Server on the RDP server side (Win2012R2) couldn't seem to work (with the error message - Could not open Dynamic Virtual Channel: 1  00000001) after the RDP session has been established.

For the RDP client side on Windows 10, the RDP client process has successfully loaded SocksOverRDP-Plugin.dll (verified by tasklist /m command ) with the message box prompt.

For your advice, please

**Comment by earthquake** [comment]
Hi,

Sorry for the late reply, I was exceptionally busy in the last two weeks. The error code 00000001 means ERROR_INVALID_FUNCTION, which most probably means and usually comes up when the RDP channel was not established. Did you connect to the server with the Remote Desktop Client and then used the server component (exe)?
It seems to me that you just logged into the server somehow else and tried to use the exe.

Let me know how it goes. Your reply might be important for other users.

**Comment by earthquake** [comment]
See closed issue: https://github.com/nccgroup/SocksOverRDP/issues/1

**Comment by earthquake** [comment]
Ignored thread as usual. Seems like a user error, therefore closed.
