### ISSUE TITLE
SOCKS over VMWare Horizon?

### ISSUE THREAD

**Issue by RoganDawes** [nccgroup/SocksOverRDP#3]
Thanks for the hard work you put into this tool.

I was wondering if you had looked at the VMWare Horizon VDI Desktop protocol? It also supports connecting local devices such as USB, so it seems like there may be a chance that this could be extended to work with the Horizons protocol as well as RDP and Citrix.

**Comment by earthquake** [comment]
Hi Rogan,

To be frank, it is unlikely that I am going to be doing that. I quickly googled and found no documentation (there might be some but could not find in a few mins), also I do not really have access to an environment.

**Comment by RoganDawes** [comment]
Fair enough! Thanks for taking the time to consider it.

**Comment by earthquake** [comment]
Of course. If you decide to go for it, feel free to reach out, I am happy to help.
