### ISSUE TITLE
Unix support?

### ISSUE THREAD

**Issue by jkroepke** [nccgroup/SocksOverRDP#7]
Hi there!

I'm currently running MacOS and I'm interest if it's possible to support FreeRDP.

Look at README.md
> In case you want to use it from Unix, give FreeRDP a try, it has released a similar module in about the same time as this tool was released.

Could you explain more?

I'm currently testing rdp2tcp (https://github.com/V-E-O/rdp2tcp). It works fine for SSH, but if i'm using a Browser which sents tons a requests, rdp2tcp stop working on the server or client side. Looks like It cant handle multiple connections well.

**Comment by earthquake** [comment]
Hi @jkroepke,

I am sorry but I will not be able to help you with that. FreeRDP has similar support for Socks proxy/portforwarding over RDP, like this project, but also this project has nothing to do FreeRDP or its code, so I cannot advise you about that.

The only advice I can give you to do that same as I would if I were you, google FreeRDP + SOCKS proxy and find the solution for your problem.

Kind Regards,

**Comment by jkroepke** [comment]
Hi @earthquake 

thats why I raised the issue there.

I couldn't not see that FreeRDP supports socks proxy in a native way.

FreeRDP implement an adapter/plugin for the 10 years old RDP2TCP, but this implement has no maintainer and has serious bugs.

**Comment by earthquake** [comment]
@jkroepke I understood that, but this repository has nothing to do with FreeRDP, RDP2TCP or Unices, therefore this issue is not related to this repository.
