### ISSUE TITLE
Mitigations

### ISSUE THREAD

**Issue by s0i37** [nccgroup/SocksOverRDP#9]
Hello.
It's really works! It works even without rdpclip.
But how to prevent it?

**Comment by earthquake** [comment]
Hi @s0i37,

Thanks for testing the tool. Could you take an additional look on the readme if that answers your question? Thanks.

**Comment by earthquake** [comment]
Sorry, my bad. I assumed that I had the solution in the readme, but it only had a few word about it and mostly explaining Citrix. Now a one-liner was added. Thanks for raising it.
